// Generated by CoffeeScript 1.10.0
(function() {
  var _query, path, query, ref, value;

  ref = process.argv.slice(2), path = ref[0], query = ref[1], value = ref[2];

  if ((path != null) && (query != null)) {
    _query = require("./query");
    _query({
      path: path,
      query: query,
      value: value
    }).then(function(result) {
      return console.log(result);
    });
  } else {
    console.error("yaml: insufficient arguments");
    console.error("yaml <path> <query>");
  }

}).call(this);
