// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    readingPath: function(error, path) {
      if (path === "-") {
        console.error("yaml: error reading from stdin");
      } else {
        console.error("yaml: error reading from " + path);
      }
      return process.exit(-1);
    },
    parsingYAML: function(error) {
      console.error("yaml: error parsing YAML\n" + error.message);
      return process.exit(-1);
    },
    formattingYAML: function(error) {
      console.error("yaml: unable to format result as YAML\n" + error.message);
      return process.exit(-1);
    },
    parsingJSON: function(error) {
      console.error("yaml: error parsing JSON\n" + error.message);
      return process.exit(-1);
    },
    formattingJSON: function(error) {
      console.error("yaml: unable to format result as JSON\n" + error.message);
      return process.exit(-1);
    },
    parsingTOML: function(error) {
      console.error("yaml: error parsing TOML\n" + error.message);
      return process.exit(-1);
    },
    formattingTOML: function(error) {
      console.error("yaml: unable to format result as TOML\n" + error.message);
      return process.exit(-1);
    }
  };

}).call(this);
