// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    readingPath: function(error, path) {
      if (path === "-") {
        console.error("yaml: error reading from stdin");
      } else {
        console.error("yaml: error reading from " + path);
      }
      return process.exit(-1);
    },
    parsingYAML: function(error) {
      console.error("yaml: error parsing YAML\n" + error.message);
      return process.exit(-1);
    },
    formattingYAML: function(error) {
      console.error("yaml: unable to format result as YAML\n" + error.message);
      return process.exit(-1);
    }
  };

}).call(this);
