// Generated by CoffeeScript 1.12.7
(function() {
  var YAML, call, isArray, isDefined, isObject, path, promise, ref, ref1, reference,
    slice = [].slice;

  ref = require("fairmont"), call = ref.call, isDefined = ref.isDefined, isObject = ref.isObject, isArray = ref.isArray;

  YAML = require("./yaml");

  ref1 = process.argv.slice(2), path = ref1[0], reference = ref1[1];

  if ((path != null) && (reference != null)) {
    promise = call(function*() {
      var current, i, j, key, keys, last, len, ref2, result, root;
      root = current = (yield YAML.read(path));
      ref2 = reference.split("."), keys = 2 <= ref2.length ? slice.call(ref2, 0, i = ref2.length - 1) : (i = 0, []), last = ref2[i++];
      for (j = 0, len = keys.length; j < len; j++) {
        key = keys[j];
        current = current[key];
      }
      result = current[last];
      return YAML.write(result);
    });
    promise["catch"](function(error) {
      console.error("yaml get: error while reading file " + error.message);
      return process.exit(1);
    });
  } else {
    console.error("yaml get: insufficient arguments");
    console.error("yaml get <path> <reference>");
    process.exit(1);
  }

}).call(this);
