// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    get: function(object, key) {
      var index, match, ref;
      if ((match = key.match(/^([^\[]+)\[(\d+)\]$/)) != null) {
        ref = match.slice(1), key = ref[0], index = ref[1];
        return object[key][index];
      } else {
        return object[key];
      }
    },
    set: function(object, key, value) {
      var index, match, ref;
      if ((match = key.match(/^([^\[]+)\[(\d+)\]$/)) != null) {
        ref = match.slice(1), key = ref[0], index = ref[1];
        return object[key][index] = value;
      } else {
        return object[key] = value;
      }
    }
  };

}).call(this);
