// Generated by CoffeeScript 1.10.0
(function() {
  var YAML, call, get, isArray, isObject, path, read, ref, ref1, ref2, reference, set, value,
    slice = [].slice;

  ref = require("fairmont"), call = ref.call, read = ref.read, isObject = ref.isObject, isArray = ref.isArray;

  YAML = require("js-yaml");

  ref1 = require("./reference"), get = ref1.get, set = ref1.set;

  ref2 = process.argv.slice(2), path = ref2[0], reference = ref2[1], value = ref2[2];

  if ((path != null) && (reference != null) && (value != null)) {
    call(function*() {
      var current, i, j, key, keys, last, len, ref3, result, root;
      root = current = YAML.safeLoad((yield read(path)));
      ref3 = reference.split("."), keys = 2 <= ref3.length ? slice.call(ref3, 0, i = ref3.length - 1) : (i = 0, []), last = ref3[i++];
      for (j = 0, len = keys.length; j < len; j++) {
        key = keys[j];
        current = get(current, key);
      }
      set(current, last, value);
      result = YAML.safeDump(root);
      return console.log(result);
    });
  } else {
    console.error("yaml set: insufficient arguments");
    console.error("yaml set <path> <reference> <value>");
    process.exit(-1);
  }

}).call(this);
