// Generated by CoffeeScript 1.10.0
(function() {
  var YAML, call, isArray, isObject, path, read, ref, ref1, reference, value,
    slice = [].slice;

  ref = require("fairmont"), call = ref.call, read = ref.read, isObject = ref.isObject, isArray = ref.isArray;

  YAML = require("js-yaml");

  ref1 = process.argv.slice(2), path = ref1[0], reference = ref1[1], value = 3 <= ref1.length ? slice.call(ref1, 2) : [];

  if ((path != null) && (reference != null) && (value != null)) {
    call(function*() {
      var current, i, j, key, keys, last, len, ref2, result, root;
      root = current = YAML.safeLoad((yield read(path)));
      ref2 = reference.split("."), keys = 2 <= ref2.length ? slice.call(ref2, 0, i = ref2.length - 1) : (i = 0, []), last = ref2[i++];
      for (j = 0, len = keys.length; j < len; j++) {
        key = keys[j];
        current = current[key];
      }
      current[last] = value.join(" ");
      result = YAML.safeDump(root);
      return console.log(result);
    });
  } else {
    console.error("yaml set: insufficient arguments");
    console.error("yaml set <path> <reference> <value>");
    process.exit(-1);
  }

}).call(this);
