// Generated by CoffeeScript 1.12.7
(function() {
  var YAML, async, errors, isArray, isObject, read, ref;

  ref = require("fairmont"), async = ref.async, read = ref.read, isObject = ref.isObject, isArray = ref.isArray;

  YAML = require("js-yaml");

  errors = require("./errors");

  module.exports = {
    read: async(function*(_path) {
      var data, error, path, yaml;
      path = _path === "-" ? process.stdin : _path;
      try {
        yaml = (yield read(path));
      } catch (error1) {
        error = error1;
        errors.readingPath(error, path);
      }
      try {
        data = YAML.safeLoad(yaml);
      } catch (error1) {
        error = error1;
        errors.parsingYAML(error);
      }
      return data;
    }),
    write: function(data) {
      var error, result;
      result = (function() {
        if (data != null) {
          if (isObject(data)) {
            try {
              return YAML.safeDump(data);
            } catch (error1) {
              error = error1;
              return errors.formatYAML(error);
            }
          } else if (isArray(data)) {
            return data.join("\n");
          } else {
            return data.toString();
          }
        } else {
          return "";
        }
      })();
      return console.log(result);
    }
  };

}).call(this);
